from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(500, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_7.setGeometry(QtCore.QRect(0, 90, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_7.setFont(font)
        self.btn_7.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_7.setObjectName("btn_7")
        self.btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_8.setGeometry(QtCore.QRect(100, 90, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_8.setFont(font)
        self.btn_8.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_8.setObjectName("btn_8")
        self.btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_9.setGeometry(QtCore.QRect(200, 90, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_9.setFont(font)
        self.btn_9.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_9.setObjectName("btn_9")
        self.btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_4.setGeometry(QtCore.QRect(0, 240, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_4.setFont(font)
        self.btn_4.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_4.setObjectName("btn_4")
        self.btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_6.setGeometry(QtCore.QRect(200, 240, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_6.setFont(font)
        self.btn_6.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_6.setObjectName("btn_6")
        self.btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_5.setGeometry(QtCore.QRect(100, 240, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_5.setFont(font)
        self.btn_5.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_5.setObjectName("btn_5")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(0, 390, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_1.setFont(font)
        self.btn_1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_1.setObjectName("btn_1")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(200, 390, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_3.setFont(font)
        self.btn_3.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_3.setObjectName("btn_3")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(100, 390, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_2.setFont(font)
        self.btn_2.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_2.setObjectName("btn_2")
        self.btn_result = QtWidgets.QPushButton(self.centralwidget)
        self.btn_result.setGeometry(QtCore.QRect(300, 390, 200, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_result.setFont(font)
        self.btn_result.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.btn_result.setObjectName("btn_result")
        self.btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.btn_plus.setGeometry(QtCore.QRect(300, 240, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_plus.setFont(font)
        self.btn_plus.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_plus.setObjectName("btn_plus")
        self.btn_ = QtWidgets.QPushButton(self.centralwidget)
        self.btn_.setGeometry(QtCore.QRect(400, 90, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_.setFont(font)
        self.btn_.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_.setObjectName("btn_")
        self.btn_min = QtWidgets.QPushButton(self.centralwidget)
        self.btn_min.setGeometry(QtCore.QRect(300, 90, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_min.setFont(font)
        self.btn_min.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_min.setObjectName("btn_min")
        self.btn_del = QtWidgets.QPushButton(self.centralwidget)
        self.btn_del.setGeometry(QtCore.QRect(400, 240, 100, 150))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_del.setFont(font)
        self.btn_del.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.btn_del.setObjectName("btn_del")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_function()

        self.is_equel = False


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutomaticProgramOpener"))
        self.label.setText(_translate("MainWindow", "0"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_result.setText(_translate("MainWindow", "="))
        self.btn_plus.setText(_translate("MainWindow", "+"))
        self.btn_.setText(_translate("MainWindow", "*"))
        self.btn_min.setText(_translate("MainWindow", "-"))
        self.btn_del.setText(_translate("MainWindow", "/"))

    def add_function(self):
        self.btn_1.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_1.text()))
        self.btn_2.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_2.text()))
        self.btn_3.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_3.text()))
        self.btn_4.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_4.text()))
        self.btn_5.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_5.text()))
        self.btn_6.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_6.text()))
        self.btn_7.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_7.text()))
        self.btn_8.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_8.text()))
        self.btn_9.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_9.text()))
        self.btn_plus.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_plus.text()))
        self.btn_del.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_del.text()))
        self.btn_min.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_min.text()))
        self.btn_.clicked.connect(lambda: self.actions_with_the_calculator(self.btn_.text()))

        self.btn_result.clicked.connect(self.result)

    def actions_with_the_calculator(self, number):
        if len(self.label.text()) < 20 or (len(self.label.text()) == 20 and number == "="):
            if (len(self.label.text()) == 18 and number in {"1", "2", "3", "4", "5", "6", "7", "8", "9"}):
                if self.label.text()[-1] in {"/", "*", "-", "+"} and (number in {"1", "2", "3", "4", "5", "6", "7", "8", "9"}):
                    self.label.setText(self.label.text() + number)
                elif self.label.text()[-1] in {"1", "2", "3", "4", "5", "6", "7", "8", "9"}:
                    self.label.setText(self.label.text() + number)
            elif (len(self.label.text()) < 18):
                if self.label.text() in {"0", "/", "*", "+"} or self.is_equel:
                    self.label.setText(number)
                    self.is_equel = False
                else:
                    if self.label.text()[-1] in {"/", "*", "-", "+"} and (number in {"1", "2", "3", "4", "5", "6", "7", "8", "9"}):
                        self.label.setText(self.label.text() + number)
                    elif self.label.text()[-1] in {"1", "2", "3", "4", "5", "6", "7", "8", "9"}:
                        self.label.setText(self.label.text() + number)

    def result(self):
        if len(self.label.text()) == 1 and self.label.text() in {"/", "*", "-", "+"}:
            res = 0
        elif any(op in self.label.text() for op in {"/", "+", "-", "*"}):
            res = eval(self.label.text())
            if isinstance(res, float) and res.is_integer():
                res = int(res)
        else:
            res = int(self.label.text())
        self.label.setText("Res: " + str(round(res, 3)))
        self.is_equel = True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
